### ISSUE TITLE
1.18.2 Fabric mod version when?

### ISSUE THREAD

**Issue by LowLightGlb** [simon-mc28/Better-McDonalds-Mod-Forge#3]

**Comment by simon-mc28** [comment]
I will probably not develop anything below 1.20.1. But you can download my Fabric version from [curseforge](https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod). the github repsoitory is available [here](https://github.com/simon-mc28/Better-McDonalds-Mod-Fabric)
